### PR TITLE
German localization added

### PR DESCRIPTION
**Pull request by mpbraendle**
German localization added

### CODE REVIEW

**Comment by ajnyga** [comment]
Thanks, I will merge this. Let me know if any other features are needed here. We currently only have one journal using this plugin, so all feedback is welcome.

**Comment by mpbraendle** [comment]
We are currently migrating our journals on a OJS 3.1 test server and detected a few problems with the standard HTML article viewer plugin: non-scrollable content on iOS, and every HTML file must be edited in the header to load the CSS styles (we would have to edit >100 HTML files).
Your plugin runs fine and solves these problems easily. Thank you. Unfortunately, the test server is behind a firewall, so you can't see the results. Here an article on the OJS 2 production server that includes embedded videos: https://www.psychoanalyse-journal.ch/article/view/jfp.59.2/926
I will soon add French and Italian localizations as well to your plugin.

**Comment by ajnyga** [comment]
Great to hear! It was exactly the problems with iOS why I made the plugin. It had problems both with scrolling and anchor links that are usually used for linking references in HTML articles.

I will prepare the plugin for a release to the plugin gallery by the end of the year. French and Italian locales are very welcome!

**Comment by mpbraendle** [comment]
For Italian I can in the first instance only provide a machine translation. I will later let it check by one of our Italian-speaking journal editors. French should be fine.

**Comment by ajnyga** [comment]
Luckily there is not that much to translate :)

**Pull request merged**
